version: '3.9'

services:
  client:
    build: requirements/client
    ports:
      - "8080:8080"
    volumes:
      - ./data/client:/app
    networks:
      - mynet

  postgres:
    build: requirements/db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=trevor
      - POSTGRES_PASSWORD=toto
      - POSTGRES_DB=transcendance
    networks:
      mynet:
        ipv4_address: '172.18.0.43'
  server:
    build: requirements/server
    ports:
      - "4244:4244"
    volumes:
      - ./data/server:/app
    networks:
      mynet:
        ipv4_address: '172.18.0.42'
  redis:
    image: redis:7-bookworm
    ports:
      - "6666:6379"
    volumes:
      - redis_data:/data
    networks:
      mynet:
        ipv4_address: '172.18.0.44'

networks:
  mynet:
    ipam:
      config:
        - subnet: '172.18.0.0/16'

volumes:
  postgres_data:
  redis_data:
