name: CI/CD for NestJS


on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: Projet_en_cours/Transcendance/ft_transcendance

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Set working directory for server
        run: cd ft_transcendance/data/server
        working-directory: ${{ github.workspace }}/Projet_en_cours/Transcendance/ft_transcendance/data/server

      - name: Install server dependencies
        run: npm install

      - name: Build server
        run: npm run build

      - name: Start server
        run: npm start
