name: CI/CD for serveur ft_transcendance

on:
  push:
    branches:
      - Back-end_start

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: data/server

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Set working directory
        run: cd data/server
        working-directory: ${{ github.workspace }}

      - name: Install dependencies and run tests
        run: |
          npm install
          npm test
          npm run build
          npm start
